install-buildtools-make: fix make 4.2.1 sanity check
For alma-8, debian-10 and opensuse-15.2, with the 'kirkstone' Yocto
Project 4.0 release a new sanity check for make 4.2.1 is throwing an
error causing the containers to fail to build.

"""
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    make version 4.2.1 is known to have issues on Centos/OpenSUSE and other non-Ubuntu systems. Please use a buildtools-make-tarball or a newer version of make.
"""

Signed-off-by: Tim Orling <tim.orling@konsulko.com>