all: Install Python virtualenv package from distro
The Python virtualenv package is provided by all distros.  We were
installing it with pip, however recent changes in Python produce
an error message:

  error: externally-managed-environment

This uses the package provided by the distro instead.

CentOS 7 calls the package python-virtualenv, but the virtualenv
command functions correctly with python3.

Signed-off-by: Rob Woolley <rob.woolley@windriver.com>